# Feature engineering
## Estancia de investigación Maestría de Ciencia de Datos
## Aide Jazmín González Cruz

### 1. Carga de librerías

In [1]:
import pandas as pd
import numpy as np
import sys
import os
from os.path import dirname
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')
sys.path.append(dirname('../src'))
from src.utils import utils

### 2. Carga de datos

In [2]:
df = utils.load_df("../Data/transformation.pkl")
df

,newid,cx_curp,glucosa,colesterol,trigliceridos,hdl,ldl,presion_arterial,hba1c,plaquetas,...,renal_años_int,sistolica_a,diastolica_a,num_consultas,target,hta_dx_años_flt,hta_dx_años_int,fecha_consulta_corta,medecine_code,medecine_name
0,3287431AAAZ581217189U5PC3,AAAZ581217189U5PC3,NaN,NaN,NaN,NaN,NaN,120/80,NaN,NaN,...,0,120.0,80.0,1,NaN,0.000000,0,2014-09-09,NaN,NaN
1,3325345AAAZ581217189U5PC3,AAAZ581217189U5PC3,448,NaN,NaN,NaN,NaN,125/75,NaN,NaN,...,0,125.0,75.0,2,NaN,0.000000,0,2014-10-16,NaN,NaN
2,3365279AAAZ581217189U5PC3,AAAZ581217189U5PC3,391|0,NaN,NaN,NaN,NaN,120/80,NaN,NaN,...,0,120.0,80.0,3,NaN,0.000000,0,2014-11-25,NaN,NaN
3,3406597AAAZ581217189U5PC3,AAAZ581217189U5PC3,0|0,NaN,NaN,NaN,NaN,120/80,NaN,NaN,...,0,120.0,80.0,4,NaN,0.000000,0,2015-01-07,NaN,NaN
4,3440661AAAZ581217189U5PC3,AAAZ581217189U5PC3,0|0,NaN,NaN,NaN,NaN,120/80,NaN,NaN,...,0,120.0,80.0,5,NaN,0.000000,0,2015-02-09,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,6278826ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,92|0,NaN,NaN,NaN,NaN,120/70,NaN,NaN,...,0,120.0,70.0,195,2.0,10.918910,10,2021-04-14,NaN,NaN
4995,6301698ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,196,2.0,10.973689,10,2021-05-04,NaN,NaN
4996,6330964ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,197,2.0,11.031326,11,2021-05-25,NaN,NaN
4997,6345416ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,NaN,198,2.0,11.058667,11,2021-06-04,NaN,NaN
4998,6382480ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,105|0,NaN,NaN,NaN,NaN,120/70,NaN,NaN,...,0,120.0,70.0,199,2.0,11.135263,11,2021-07-02,NaN,NaN

- Variables categoricas, existencia laboratorios

In [3]:
df['lab_colestero'] = np.where(pd.isna(df['colesterol']),0,1)
df['lab_trigliceridos'] = np.where(pd.isna(df['colesterol']),0,1)
df['lab_hdl'] = np.where(pd.isna(df['colesterol']),0,1)
df['lab_ldl'] = np.where(pd.isna(df['colesterol']),0,1)
df['lab_hba1c'] = np.where(pd.isna(df['colesterol']),0,1)
df['lab_plaquetas'] = np.where(pd.isna(df['colesterol']),0,1)
df['lab_creatinina'] = np.where(pd.isna(df['colesterol']),0,1)
df['lab_acido_urico'] = np.where(pd.isna(df['colesterol']),0,1)
df['lab_urea'] = np.where(pd.isna(df['colesterol']),0,1)
df['lab_tfg'] = np.where(pd.isna(df['colesterol']),0,1)

- Clasificación lista mexicana

In [4]:
from src.utils import processing as proc

In [5]:
df = proc.lista_mex_enf(df)

In [6]:
df.shape

(4999, 137)

In [7]:
df

,newid,cx_curp,glucosa,colesterol,trigliceridos,hdl,ldl,presion_arterial,hba1c,plaquetas,...,heridas,efec_cuerpos_extr_pen_orificios_naturales,quemaduras_corrosiones,envenenamiento_efectos_tox,sindrome_maltrato,comp_precoces_traumatismos,comp_aten_med_qx_no_clasif,sec_traumatismos_envenenamiento_causas_ext,ot_efec_causas_ext_comp_traumatismos,tumores_malig_labio_bucal_faringe
0,3287431AAAZ581217189U5PC3,AAAZ581217189U5PC3,NaN,NaN,NaN,NaN,NaN,120/80,NaN,NaN,...,0,0,0,0,1,1,0,0,0,0
1,3325345AAAZ581217189U5PC3,AAAZ581217189U5PC3,448,NaN,NaN,NaN,NaN,125/75,NaN,NaN,...,0,0,0,0,1,1,0,0,0,0
2,3365279AAAZ581217189U5PC3,AAAZ581217189U5PC3,391|0,NaN,NaN,NaN,NaN,120/80,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
3,3406597AAAZ581217189U5PC3,AAAZ581217189U5PC3,0|0,NaN,NaN,NaN,NaN,120/80,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4,3440661AAAZ581217189U5PC3,AAAZ581217189U5PC3,0|0,NaN,NaN,NaN,NaN,120/80,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,6278826ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,92|0,NaN,NaN,NaN,NaN,120/70,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4995,6301698ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,0,0,0
4996,6330964ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,0,0,0
4997,6345416ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,0,0,0
4998,6382480ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,105|0,NaN,NaN,NaN,NaN,120/70,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

- Medicamentos

In [8]:
df.columns.values.tolist()

['newid',
 'cx_curp',
 'glucosa',
 'colesterol',
 'trigliceridos',
 'hdl',
 'ldl',
 'presion_arterial',
 'hba1c',
 'plaquetas',
 'creatinina',
 'acido_urico',
 'urea',
 'peso',
 'altura',
 'tfg',
 'imc',
 'fuente',
 'in_consulta',
 'fecha_nacimiento',
 'sexo',
 'medicamentos',
 'codigos_cie',
 'diagnosticos',
 'fecha_consulta',
 'sistolica',
 'diastolica',
 'glucosa1',
 'glucosa2',
 'edad',
 'hta',
 'dm_cie',
 'hta_cie',
 'renal_cie',
 'fecha_laboratorio',
 'dif_date_lab',
 'dif_date_lab_from_ini',
 'occurance_counter',
 'año_dx_dm',
 'año_dx_hta',
 'year_consulta',
 'imc_calculado',
 'imc_range',
 'vent_ini_aux',
 'vent_ini_consul',
 'vent_entre_consul',
 'vent_years_consul',
 'vent_ini_lab',
 'vent_entre_lab',
 'dm_cie_unic',
 'dm_años_flt',
 'dm_años_int',
 'hta_cie_unic',
 'hta_años_flt',
 'hta_años_int',
 'renal_cie_unic',
 'renal_años_flt',
 'renal_años_int',
 'sistolica_a',
 'diastolica_a',
 'num_consultas',
 'target',
 'hta_dx_años_flt',
 'hta_dx_años_int',
 'fecha_consulta_corta',
 'medecine_code',
 'medecine_name',
 'lab_colestero',
 'lab_trigliceridos',
 'lab_hdl',
 'lab_ldl',
 'lab_hba1c',
 'lab_plaquetas',
 'lab_creatinina',
 'lab_acido_urico',
 'lab_urea',
 'lab_tfg',
 'enf_inf_intestinales',
 'tuberculosis',
 'ot_enf_bacterianas',
 'inf_trans_pred_sexual',
 'ot_enf_inf_y_paras_y_efec_tardios',
 'enf_viricas',
 'rickettsiosis_y_ot_enf__protozoarios',
 'tumores_malig_labio_bucal_faringe',
 'tumores_malig_organos',
 'tumores_malig_org_respiratorios_intratoracicos',
 'tumores_malig_huesos_articulares_conjuntivo_piel_mama',
 'tumores_malig_org_genitourinarios',
 'tumores_malig_otros_sitios_ne',
 'tumores_malig_tejido_linf_org_hematop',
 'tumores_malig_sitios_mul_indep',
 'tumores_insitu',
 'tumores_benignos',
 'tumores_comp_incierto_desc',
 'enf_sangre_org_hematop',
 'enf_endocrinas',
 'desnutricion_ot_deficiencias',
 'trastornos_mentales',
 'enf_sist_nervioso',
 'enf_ojo_anexos',
 'enf_oido_apofisis_mastoides',
 'fiebre_y_enf_cardiacas_reumaticas',
 'enf_hipertensivas',
 'enf_isquemicas_corazon',
 'enf_circulacion_pulmonar_enf_corazon',
 'enf_cerebrovasculares',
 'otras_enf_aparato_vasc',
 'inf_y_enf_vias_respiratorias_sup',
 'otras_enf_aparato_resp',
 'enf_cavidad_bucal_glandulas_salivales',
 'enf_ot_partes_aparato_digestivo',
 'enf_piel_tejido_subcutaneo',
 'enf_sist_osteomuscular_y_tejido',
 'enf_aparato_urinario',
 'enf_org_genitales_masculinos',
 'trastornos_mama',
 'enf_org_genitales_femeninos',
 'trastornos_sist_genitourinario_consec_proced',
 'causas_obstetricas_directas',
 'parto',
 'causas_obstetricas_indirectas',
 'malformaciones_congenitas',
 'sintomas_signos_hallazgos_anormales_clin_lab_no_clasif',
 'fracturas',
 'luxaciones_esguinces_torceduras',
 'traumatismos_int_intracraneales_y_otr',
 'heridas',
 'efec_cuerpos_extr_pen_orificios_naturales',
 'quemaduras_corrosiones',
 'envenenamiento_efectos_tox',
 'sindrome_maltrato',
 'comp_precoces_traumatismos',
 'comp_aten_med_qx_no_clasif',
 'sec_traumatismos_envenenamiento_causas_ext',
 'ot_efec_causas_ext_comp_traumatismos',
 'tumores_malig_labio_bucal_faringe ']

- Seleccionando la fecha más antigua por paciente

In [9]:
df_time = df.groupby('cx_curp')['fecha_consulta'].min()
df_time = pd.DataFrame(df_time).sort_values('cx_curp')
print(df_time.shape)
df_time.head(5)

(55, 1)

                            fecha_consulta
cx_curp
AAAZ581217189U5PC3 2014-09-09 08:51:37.470
AADV5603014KS44QC1 2004-08-26 18:05:31.090
AEDJ750301XGAEGRC1 2007-01-12 14:14:18.083
AOCC511229UR4RIRC3 2012-05-18 09:13:41.643
BOLM631201LV35XPC1 2005-11-28 15:20:39.297

In [10]:
df_time['year_consulta'] = df_time['fecha_consulta'].dt.year
df_time.head(5)

                            fecha_consulta  year_consulta
cx_curp
AAAZ581217189U5PC3 2014-09-09 08:51:37.470           2014
AADV5603014KS44QC1 2004-08-26 18:05:31.090           2004
AEDJ750301XGAEGRC1 2007-01-12 14:14:18.083           2007
AOCC511229UR4RIRC3 2012-05-18 09:13:41.643           2012
BOLM631201LV35XPC1 2005-11-28 15:20:39.297           2005

- Obteniendo año dx HTA

In [11]:
# Ajustar dx hipertensión porque no esta
df_hta = df[~pd.isna(df['medecine_code'])].groupby('cx_curp')['fecha_consulta'].min()
df_hta = pd.DataFrame(df_hta)
df_hta['año_dx_hta'] = pd.to_datetime(df_hta['fecha_consulta'],\
                                            format='%y-%m-%d %H:%M:%S').dt.strftime('%Y')
df_hta = df_hta.sort_values('cx_curp')
print(df_hta.shape)
df_hta.head(5)

(54, 2)

                            fecha_consulta año_dx_hta
cx_curp
AAAZ581217189U5PC3 2015-05-25 09:38:38.897       2015
AADV5603014KS44QC1 2009-10-28 17:25:02.853       2009
AEDJ750301XGAEGRC1 2012-08-23 18:15:56.640       2012
AOCC511229UR4RIRC3 2012-07-18 09:46:09.020       2012
BOLM631201LV35XPC1 2013-01-09 16:36:32.760       2013

In [12]:
df_time_hta = pd.merge(df_time, df_hta, on = ["cx_curp"], how="left")
df_time_hta.rename(columns = {'fecha_consulta_x':'fecha_consulta'}, inplace = True)
df_time_hta.drop('fecha_consulta_y', inplace=True, axis=1)
df_time_hta['fecha_consulta'] = pd.to_datetime(df_time_hta['fecha_consulta'],\
                                            format='%y-%m-%d %H:%M:%S').dt.strftime('%Y-%m-%d')
display(df_time_hta.head(5))
print(df_time_hta.shape)

                   fecha_consulta  year_consulta año_dx_hta
cx_curp
AAAZ581217189U5PC3     2014-09-09           2014       2015
AADV5603014KS44QC1     2004-08-26           2004       2009
AEDJ750301XGAEGRC1     2007-01-12           2007       2012
AOCC511229UR4RIRC3     2012-05-18           2012       2012
BOLM631201LV35XPC1     2005-11-28           2005       2013

(55, 3)

- Quitando pacientes con los 2 DX

In [13]:
df_time_hta["descartados"] = np.where((df_time_hta["year_consulta"]==df_time_hta["año_dx_hta"]),1,0)
df_time_hta = df_time_hta[df_time_hta["descartados"]==0]
display(df_time_hta.head(5))
print(df_time_hta.shape)

                   fecha_consulta  year_consulta año_dx_hta  descartados
cx_curp
AAAZ581217189U5PC3     2014-09-09           2014       2015            0
AADV5603014KS44QC1     2004-08-26           2004       2009            0
AEDJ750301XGAEGRC1     2007-01-12           2007       2012            0
AOCC511229UR4RIRC3     2012-05-18           2012       2012            0
BOLM631201LV35XPC1     2005-11-28           2005       2013            0

(55, 4)

In [14]:
df = pd.DataFrame(df).sort_values(['cx_curp','fecha_consulta'])
df

,newid,cx_curp,glucosa,colesterol,trigliceridos,hdl,ldl,presion_arterial,hba1c,plaquetas,...,heridas,efec_cuerpos_extr_pen_orificios_naturales,quemaduras_corrosiones,envenenamiento_efectos_tox,sindrome_maltrato,comp_precoces_traumatismos,comp_aten_med_qx_no_clasif,sec_traumatismos_envenenamiento_causas_ext,ot_efec_causas_ext_comp_traumatismos,tumores_malig_labio_bucal_faringe
0,3287431AAAZ581217189U5PC3,AAAZ581217189U5PC3,NaN,NaN,NaN,NaN,NaN,120/80,NaN,NaN,...,0,0,0,0,1,1,0,0,0,0
1,3325345AAAZ581217189U5PC3,AAAZ581217189U5PC3,448,NaN,NaN,NaN,NaN,125/75,NaN,NaN,...,0,0,0,0,1,1,0,0,0,0
2,3365279AAAZ581217189U5PC3,AAAZ581217189U5PC3,391|0,NaN,NaN,NaN,NaN,120/80,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
3,3406597AAAZ581217189U5PC3,AAAZ581217189U5PC3,0|0,NaN,NaN,NaN,NaN,120/80,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4,3440661AAAZ581217189U5PC3,AAAZ581217189U5PC3,0|0,NaN,NaN,NaN,NaN,120/80,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,6278826ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,92|0,NaN,NaN,NaN,NaN,120/70,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4995,6301698ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,0,0,0
4996,6330964ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,0,0,0
4997,6345416ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,0,0,0,0
4998,6382480ZEPL5503219FZQ6QC2,ZEPL5503219FZQ6QC2,105|0,NaN,NaN,NaN,NaN,120/70,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

- Función para crear ventanas

In [15]:
from dateutil.relativedelta import relativedelta

In [16]:
df_time_hta= df_time_hta.reset_index()
df_time_hta = pd.DataFrame(df_time_hta)
df_time_hta['fecha_consulta']= pd.to_datetime(df_time_hta['fecha_consulta'])
df_time_hta

               cx_curp fecha_consulta  year_consulta año_dx_hta  descartados
0   AAAZ581217189U5PC3     2014-09-09           2014       2015            0
1   AADV5603014KS44QC1     2004-08-26           2004       2009            0
2   AEDJ750301XGAEGRC1     2007-01-12           2007       2012            0
3   AOCC511229UR4RIRC3     2012-05-18           2012       2012            0
4   BOLM631201LV35XPC1     2005-11-28           2005       2013            0
5   CAAE51120998X96PC1     2010-11-24           2010       2011            0
6   CAAJ770616UNX3HRC2     2004-09-27           2004       2009            0
7   CABM400930CPT4ZCA2     2005-01-14           2005       2011            0
8   CALT491222GG7DGRC3     2015-03-13           2015       2015            0
9   COAG580101F7ALKRC3     2019-07-26           2019       2020            0
10  COGJ5108018PI47QC1     2010-07-13           2010       2010            0
11  COPI690401V91QCRC2     2004-10-18           2004       2015            0
12  COVR310301TY2UYQC1     2007-05-23           2007       2010            0
13  CUHJ691220ZX7YDRC2     2004-09-06           2004       2010            0
14  DIJC38112055K14KA2     2004-10-21           2004       2015            0
15  DIRL630201M8ADARC1     2005-01-11           2005       2010            0
16  EAGG5405015QC44QC1     2005-04-14           2005       2012            0
17  GAMP640301UJL5SEE1     2004-10-14           2004       2018            0
18  GASG61090173W69PC1     2014-09-19           2014       2017            0
19  GOGC330501FATDSCA2     2004-09-29           2004       2009            0
20  GOML440127J80Z9PC2     2006-01-24           2006       2008            0
21  GUSJ5712286XUN73A2     2005-01-14           2005       2011            0
22  HEXE490230BS8EFVA2     2004-08-16           2004       2013            0
23  JIDR510316QA5Z4PC3     2014-12-30           2014       2014            0
24  LOAI360801BLJDERC1     2004-12-13           2004       2009            0
25  LOVM470206XDKAIMD2     2006-10-04           2006       2010            0
26  MACL740410NK1YGRC2     2004-09-14           2004       2018            0
27  MAJJ870410UVK09PC1     2006-03-06           2006       2016            0
28  MAVC341201G0YJFRC1     2004-11-09           2004       2013            0
29  MAXA480701EQOUDRC1     2003-11-19           2003       2011            0
30  MOAA5610143OU79PC2     2006-02-23           2006       2009            0
31  MOBJ380101BWUPXQC1     2009-07-24           2009       2009            0
32  MOSH731006R68EZPC2     2014-04-22           2014       2014            0
33  MOVE400201D7TZERC1     2004-12-14           2004       2006            0
34  OIMS600706LWUN8PC2     2013-11-08           2013       2016            0
35  OOCG680408JBU4ERC2     2005-04-15           2005       2009            0
36  PAGJ690411WZ0YDRC1     2007-07-12           2007       2020            0
37  PAMI6701206PHN6PC4     2017-07-14           2017       2018            0
38  PEGO194405B3QH4QC1     2006-09-08           2006       2009            0
39  PEVR470901ASKH1QC1     2004-05-25           2004       2007            0
40  PIPB6010280UNG7PC4     2014-08-01           2014       2017            0
41  PIRE6806019N4I6PC1     2009-04-24           2009       2012            0
42  ROCA5508101VD78DB4     2016-01-12           2016       2016            0
43  ROGG540607PNXOCQD4     2004-06-14           2004       2007            0
44  RORC5211012YV34CA1     2011-10-29           2011       2016            0
45  SAJB6406296LNT8PC4     2018-08-09           2018       2018            0
46  SAPL460201_WS10QC2     2004-12-29           2004       2015            0
47  SOLG360601I3NUBIA1     2004-09-28           2004       2008            0
48  VABL610430GWELKRC4     2017-01-02           2017       2017            0
49  VEMS600601JHJY2QC2     2009-04-20           2009       2015            0
50  VEVF4904172GTC8QC1     2009-04-21           2009        NaN            0
51  VIMA64070146S4BRC1     2004-09-09           2004       2017            0
52  ZACF481001A5LI4QC1     2005-11-18           2005       2009            0
53  ZAGM6412151ICF4PC4     2012-11-09           2012       2016            0
54  ZEPL5503219FZQ6QC2     2004-08-25           2004       2009            0

In [17]:
new_date = df_time_hta[df_time_hta['cx_curp']=='AAAZ581217189U5PC3'][['fecha_consulta']] 
(new_date['fecha_consulta']+pd.to_timedelta(2*365, unit = 'D')).dt.date.values[0]

datetime.date(2016, 9, 8)

In [18]:
new_date.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1 entries, 0 to 0
Data columns (total 1 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fecha_consulta  1 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 16.0 bytes

In [79]:
import pandas as pd

def dias_year(date):
    days = np.nan
    print('date-',date)
    p = pd.Period(date)
    if p.is_leap_year:
        days = 366
    else:
        days = 365
        
    return days

def fecha_ini_fin(fecha_ini):
    # Crear variable de ventanas máximas o hacer referencia a la variable años de conuslta
    #fecha_ini = datetime.timestamp(fecha_ini)
    fecha_ini = pd.to_datetime(fecha_ini)
    fecha_ini = pd.Timestamp(fecha_ini)
    print(type(fecha_ini))
    print(((fecha_ini+pd.to_timedelta(365, unit = 'D'))))
    a_ini = (fecha_ini+pd.to_timedelta(365, unit = 'D')).dt.date.values[0]
    a_fin = (fecha_ini+pd.to_timedelta(2*365, unit = 'D')).dt.date.values[0]
    
    i = a_ini.strftime('%Y-%m-%d')
    f = a_fin.strftime('%Y-%m-%d')
    
    i = dias_year(i)
    print(i)
    f = dias_year(f)
    print(f)
    
    a_ini = (fecha_ini+pd.to_timedelta(i, unit = 'D')).dt.date.values[0]
    a_fin = (fecha_ini+pd.to_timedelta(i+f, unit = 'D')).dt.date.values[0]
    
    return a_ini, a_fin

In [80]:
# Inicciando dataframe de ventanas
#df_window_s = pd.d

# Por cada paciente único
for i in range(len(df_time_hta['cx_curp'])):
    # Inicializando valores
    curp = df_time_hta['cx_curp'][i]
    fecha_ini = df_time_hta['fecha_consulta'][i] #Pasar a fecha corta
    fecha_ini2 = fecha_ini
    fecha_ini = fecha_ini.to_datetime64()
    print(fecha_ini)
    print(type(fecha_ini))
    a_ini, a_fin = fecha_ini_fin(fecha_ini2)    
    
    # ver si se agrega la fecha inicial y final de la ventana
    df_aux = df[(df['cx_curp']==curp)&\
                (df['fecha_consulta']>=fecha_ini)&\
                (df['fecha_consulta']<a_fin)].sort_values(['cx_curp','fecha_consulta'])
    df_aux
    break
    """
    # Ventana por persona
    # df_window_p = 
    
    # Recorrer sus registros
    for j in range(len(df_time_hta['cx_curp'])):
        # Listado de variables a generar
            df_window_p['cx_curp'] = curp
            df_window_p['ventana'] = j
            df_window_p['sum_num_consultas'] = 
            df_window_p['avg_num_consultas'] = 
            df_window_p['dm'] = 1
            df_window_p['renal'] = 1
            
            df_window_p['glucosa1'] = 
            df_window_p['num_med_glucosa1'] = 
            df_window_p['avg_glucosa1'] = 
            df_window_p['min_glucosa1'] = 
            df_window_p['max_glucosa1'] = 
            
            df_window_p['glucosa2'] = 
            df_window_p['num_med_glucosa2'] = 
            df_window_p['avg_glucosa2'] = 
            df_window_p['min_glucosa2'] = 
            df_window_p['max_glucosa2'] = 
            
            df_window_p['lab_colestero'] = 
            df_window_p['num_med_colesterol'] = 
            df_window_p['avg_colesterol'] = 
            df_window_p['min_colesterol'] = 
            df_window_p['max_colesterol'] = 
            
            df_window_p['lab_trigliceridos'] = 
            df_window_p['num_med_trigliceridos'] = 
            df_window_p['avg_trigliceridos'] = 
            df_window_p['min_trigliceridos'] = 
            df_window_p['max_trigliceridos'] = 
            
            df_window_p['lab_hdl'] = 
            df_window_p['num_med_hdl'] = 
            df_window_p['avg_hdl'] = 
            df_window_p['min_hdl'] = 
            df_window_p['max_hdl'] = 
            
            df_window_p['lab_ldl'] = 
            df_window_p['num_med_ldl'] = 
            df_window_p['avg_ldl'] = 
            df_window_p['min_ldl'] = 
            df_window_p['max_ldl'] = 
            
            df_window_p['presion_arterial'] = 
            df_window_p['num_med_presion_a'] = 
            df_window_p['avg_sistolica_a'] = 
            df_window_p['min_sistolica_a'] = 
            df_window_p['max_sistolica_a'] = 
            df_window_p['avg_diastolica_a'] = 
            df_window_p['min_diastolica_a'] = 
            df_window_p['max_diastolica_a'] = 
            
            df_window_p['lab_hba1c'] = 
            df_window_p['num_med_hba1c'] = 
            df_window_p['avg_hba1c'] = 
            df_window_p['min_hba1c'] = 
            df_window_p['max_hba1c'] = 
            
            df_window_p['lab_plaquetas'] = 
            df_window_p['num_med_plaquetas'] = 
            df_window_p['avg_plaquetas'] = 
            df_window_p['min_plaquetas'] = 
            df_window_p['max_plaquetas'] = 
            
            df_window_p['lab_creatinina'] = 
            df_window_p['num_med_creatinina'] = 
            df_window_p['avg_creatinina'] = 
            df_window_p['min_creatinina'] = 
            df_window_p['max_creatinina'] = 
            
            df_window_p['lab_acido_urico'] = 
            df_window_p['num_med_acido_urico'] = 
            df_window_p['avg_acido_urico'] = 
            df_window_p['min_acido_urico'] = 
            df_window_p['max_acido_urico'] = 
            
            df_window_p['lab_urea'] = 
            df_window_p['num_med_urea'] = 
            df_window_p['avg_urea'] = 
            df_window_p['min_urea'] = 
            df_window_p['max_urea'] = 
            
            df_window_p['peso'] = 
            df_window_p['num_med_peso'] = 
            df_window_p['avg_peso'] = 
            df_window_p['min_peso'] = 
            df_window_p['max_peso'] = 
            
            df_window_p['altura'] = 
            df_window_p['num_med_altura'] = 
            df_window_p['avg_altura'] = 
            df_window_p['min_altura'] = 
            df_window_p['max_altura'] = 
            
            df_window_p['lab_tfg'] = 
            df_window_p['num_med_tfg'] = 
            df_window_p['avg_tfg'] = 
            df_window_p['min_tfg'] = 
            df_window_p['max_tfg'] = 
            
            df_window_p['edad'] = 
            df_window_p['num_med_edad'] = 
            df_window_p['avg_edad'] = 
            df_window_p['min_edad'] = 
            df_window_p['max_edad'] = 
            
            df_window_p['dif_date_lab'] = 
            df_window_p['num_med_dif_date_lab'] = 
            df_window_p['avg_dif_date_lab'] = 
            df_window_p['min_dif_date_lab'] = 
            df_window_p['max_dif_date_lab'] = 
            
            df_window_p['imc_calculado'] = 
            df_window_p['num_med_imc_calculado'] = 
            df_window_p['avg_dif_imc_calculado'] = 
            df_window_p['min_dif_imc_calculado'] = 
            df_window_p['max_dif_imc_calculado'] = 
            
            df_window_p['imc_range'] = 
            
            df_window_p['num_med_vent_entre_consul'] = 
            df_window_p['avg_vent_entre_consul'] = 
            df_window_p['min_dif_vent_entre_consul'] = 
            df_window_p['max_dif_vent_entre_consul'] = 
            
            df_window_p['num_med_vent_entre_lab'] = 
            df_window_p['avg_vent_entre_lab'] = 
            df_window_p['min_dif_vent_entre_lab'] = 
            df_window_p['max_dif_vent_entre_lab'] = 
            
            df_window_p['enf_inf_intestinales'] = 
            df_window_p['num_med_enf_inf_intestinales'] = 
            df_window_p['avg_enf_inf_intestinales'] = 
   
            df_window_p['tuberculosis'] = 
            df_window_p['num_med_tuberculosis'] = 
            df_window_p['avg_tuberculosis'] = 
   
            df_window_p['ot_enf_bacterianas'] = 
            df_window_p['num_med_ot_enf_bacterianas'] = 
            df_window_p['avg_ot_enf_bacterianas'] = 
   
            df_window_p['inf_trans_pred_sexual'] = 
            df_window_p['num_med_inf_trans_pred_sexual'] = 
            df_window_p['avg_inf_trans_pred_sexual'] = 
   
            df_window_p['ot_enf_inf_y_paras_y_efec_tardios'] = 
            df_window_p['num_med_ot_enf_inf_y_paras_y_efec_tardios'] = 
            df_window_p['avg_ot_enf_inf_y_paras_y_efec_tardios'] = 
   
            df_window_p['enf_viricas'] = 
            df_window_p['num_med_enf_viricas'] = 
            df_window_p['avg_enf_viricas'] = 
   
            df_window_p['rickettsiosis_y_ot_enf__protozoarios'] = 
            df_window_p['num_med_rickettsiosis_y_ot_enf__protozoarios'] = 
            df_window_p['avg_rickettsiosis_y_ot_enf__protozoarios'] = 
   
            df_window_p['tumores_malig_labio_bucal_faringe'] = 
            df_window_p['num_med_tumores_malig_labio_bucal_faringe'] = 
            df_window_p['avg_tumores_malig_labio_bucal_faringe'] = 
   
            df_window_p['tumores_malig_organos'] = 
            df_window_p['num_med_tumores_malig_organos'] = 
            df_window_p['avg_tumores_malig_organos'] = 
   
            df_window_p['tumores_malig_org_respiratorios_intratoracicos'] = 
            df_window_p['num_med_tumores_malig_org_respiratorios_intratoracicos'] = 
            df_window_p['avg_tumores_malig_org_respiratorios_intratoracicos'] = 
   
            df_window_p['tumores_malig_huesos_articulares_conjuntivo_piel_mama'] = 
            df_window_p['num_med_tumores_malig_huesos_articulares_conjuntivo_piel_mama'] = 
            df_window_p['avg_tumores_malig_huesos_articulares_conjuntivo_piel_mama'] = 
   
            df_window_p['tumores_malig_org_genitourinarios'] = 
            df_window_p['num_med_tumores_malig_org_genitourinarios'] = 
            df_window_p['avg_tumores_malig_org_genitourinarios'] = 
   
            df_window_p['tumores_malig_otros_sitios_ne'] = 
            df_window_p['num_med_tumores_malig_otros_sitios_ne'] = 
            df_window_p['avg_tumores_malig_otros_sitios_ne'] = 
   
            df_window_p['tumores_malig_tejido_linf_org_hematop'] = 
            df_window_p['num_med_tumores_malig_tejido_linf_org_hematop'] = 
            df_window_p['avg_tumores_malig_tejido_linf_org_hematop'] = 
   
            df_window_p['tumores_malig_sitios_mul_indep'] = 
            df_window_p['num_med_tumores_malig_sitios_mul_indep'] = 
            df_window_p['avg_tumores_malig_sitios_mul_indep'] = 
   
            df_window_p['tumores_insitu'] = 
            df_window_p['num_med_tumores_insitu'] = 
            df_window_p['avg_tumores_insitu'] = 
   
            df_window_p['tumores_benignos'] = 
            df_window_p['num_med_tumores_benignos'] = 
            df_window_p['avg_tumores_benignos'] = 
   
            df_window_p['tumores_comp_incierto_desc'] = 
            df_window_p['num_med_tumores_comp_incierto_desc'] = 
            df_window_p['avg_tumores_comp_incierto_desc'] = 
   
            df_window_p['enf_sangre_org_hematop'] = 
            df_window_p['num_med_enf_sangre_org_hematop'] = 
            df_window_p['avg_enf_sangre_org_hematop'] = 
   
            df_window_p['enf_endocrinas'] = 
            df_window_p['num_med_enf_endocrinas'] = 
            df_window_p['avg_enf_endocrinas'] = 
   
            df_window_p['desnutricion_ot_deficiencias'] = 
            df_window_p['num_med_desnutricion_ot_deficiencias'] = 
            df_window_p['avg_desnutricion_ot_deficiencias'] = 
   
            df_window_p['trastornos_mentales'] = 
            df_window_p['num_med_trastornos_mentales'] = 
            df_window_p['avg_ trastornos_mentales'] = 
   
            df_window_p['enf_sist_nervioso'] = 
            df_window_p['num_med_enf_sist_nervioso'] = 
            df_window_p['avg_enf_sist_nervioso'] = 
   
            df_window_p['enf_ojo_anexos'] = 
            df_window_p['num_med_enf_ojo_anexos'] = 
            df_window_p['avg_enf_ojo_anexos'] = 
   
            df_window_p['enf_oido_apofisis_mastoides'] = 
            df_window_p['num_med_enf_oido_apofisis_mastoides'] = 
            df_window_p['avg_enf_oido_apofisis_mastoides'] = 
   
            df_window_p['fiebre_y_enf_cardiacas_reumaticas'] = 
            df_window_p['num_med_fiebre_y_enf_cardiacas_reumaticas'] = 
            df_window_p['avg_fiebre_y_enf_cardiacas_reumaticas'] = 
   
            df_window_p['enf_hipertensivas'] = 
            df_window_p['num_med_enf_hipertensivas'] = 
            df_window_p['avg_enf_hipertensivas'] = 
   
            df_window_p['enf_isquemicas_corazon'] = 
            df_window_p['num_med_enf_isquemicas_corazon'] = 
            df_window_p['avg_enf_isquemicas_corazon'] = 
   
            df_window_p['enf_circulacion_pulmonar_enf_corazon'] = 
            df_window_p['num_med_enf_circulacion_pulmonar_enf_corazon'] = 
            df_window_p['avg_enf_circulacion_pulmonar_enf_corazon'] = 
   
            df_window_p['enf_cerebrovasculares'] = 
            df_window_p['num_med_enf_cerebrovasculares'] = 
            df_window_p['avg_enf_cerebrovasculares'] = 
   
            df_window_p['otras_enf_aparato_vasc'] = 
            df_window_p['num_med_otras_enf_aparato_vasc'] = 
            df_window_p['avg_otras_enf_aparato_vasc'] = 
   
            df_window_p['inf_y_enf_vias_respiratorias_sup'] = 
            df_window_p['num_med_inf_y_enf_vias_respiratorias_sup'] = 
            df_window_p['avg_inf_y_enf_vias_respiratorias_sup'] = 
   
            df_window_p['otras_enf_aparato_resp'] = 
            df_window_p['num_med_otras_enf_aparato_resp'] = 
            df_window_p['avg_otras_enf_aparato_resp'] = 
   
            df_window_p['enf_cavidad_bucal_glandulas_salivales'] = 
            df_window_p['num_med_enf_cavidad_bucal_glandulas_salivales'] = 
            df_window_p['avg_enf_cavidad_bucal_glandulas_salivales'] = 
   
            df_window_p['enf_ot_partes_aparato_digestivo'] = 
            df_window_p['num_med_enf_ot_partes_aparato_digestivo'] = 
            df_window_p['avg_enf_ot_partes_aparato_digestivo'] = 
   
            df_window_p['enf_piel_tejido_subcutaneo'] = 
            df_window_p['num_med_enf_piel_tejido_subcutaneo'] = 
            df_window_p['avg_enf_piel_tejido_subcutaneo'] = 
   
            df_window_p['enf_sist_osteomuscular_y_tejido'] = 
            df_window_p['num_med_enf_sist_osteomuscular_y_tejido'] = 
            df_window_p['avg_enf_sist_osteomuscular_y_tejido'] = 
   
            df_window_p['enf_aparato_urinario'] = 
            df_window_p['num_med_enf_aparato_urinario'] = 
            df_window_p['avg_enf_aparato_urinario'] = 
   
            df_window_p['enf_org_genitales_masculinos'] = 
            df_window_p['num_med_enf_org_genitales_masculinos'] = 
            df_window_p['avg_enf_org_genitales_masculinos'] = 
   
            df_window_p['trastornos_mama'] = 
            df_window_p['num_med_trastornos_mama'] = 
            df_window_p['avg_trastornos_mama'] = 
   
            df_window_p['enf_org_genitales_femeninos'] = 
            df_window_p['num_med_enf_org_genitales_femeninos'] = 
            df_window_p['avg_enf_org_genitales_femeninos'] = 
   
            df_window_p['trastornos_sist_genitourinario_consec_proced'] =
            df_window_p['num_med_trastornos_sist_genitourinario_consec_proced'] = 
            df_window_p['avg_trastornos_sist_genitourinario_consec_proced'] = 
   
            df_window_p['causas_obstetricas_directas'] = 
            df_window_p['num_med_causas_obstetricas_directas'] = 
            df_window_p['avg_causas_obstetricas_directas'] = 
   
            df_window_p['parto'] = 
            df_window_p['num_med_parto'] = 
            df_window_p['avg_parto'] = 
   
            df_window_p['causas_obstetricas_indirectas'] = 
            df_window_p['num_med_causas_obstetricas_indirectas'] = 
            df_window_p['avg_causas_obstetricas_indirectas'] = 
   
            df_window_p['malformaciones_congenitas'] = 
            df_window_p['num_med_malformaciones_congenitas'] = 
            df_window_p['avg_malformaciones_congenitas'] = 
   
            df_window_p['sintomas_signos_hallazgos_anormales_clin_lab_no_clasif'] = 
            df_window_p['num_med_sintomas_signos_hallazgos_anormales_clin_lab_no_clasif'] = 
            df_window_p['avg_sintomas_signos_hallazgos_anormales_clin_lab_no_clasif'] = 
   
            df_window_p['fracturas'] = 
            df_window_p['num_med_fracturas'] = 
            df_window_p['avg_fracturas'] = 
   
            df_window_p['luxaciones_esguinces_torceduras'] = 
            df_window_p['num_med_luxaciones_esguinces_torceduras'] = 
            df_window_p['avg_luxaciones_esguinces_torceduras'] = 
   
            df_window_p['traumatismos_int_intracraneales_y_otr'] = 
            df_window_p['num_med_traumatismos_int_intracraneales_y_otr'] = 
            df_window_p['avg_traumatismos_int_intracraneales_y_otr'] = 
   
            df_window_p['heridas'] = 
            df_window_p['num_med_heridas'] = 
            df_window_p['avg_heridas'] = 
   
            df_window_p['efec_cuerpos_extr_pen_orificios_naturales'] = 
            df_window_p['num_med_efec_cuerpos_extr_pen_orificios_naturales'] = 
            df_window_p['avg_efec_cuerpos_extr_pen_orificios_naturales'] = 
   
            df_window_p['quemaduras_corrosiones'] = 
            df_window_p['num_med_quemaduras_corrosiones'] = 
            df_window_p['avg_quemaduras_corrosiones'] = 
   
            df_window_p['envenenamiento_efectos_tox'] = 
            df_window_p['num_med_envenenamiento_efectos_tox'] = 
            df_window_p['avg_envenenamiento_efectos_tox'] = 
   
            df_window_p['sindrome_maltrato'] = 
            df_window_p['num_med_sindrome_maltrato'] = 
            df_window_p['avg_sindrome_maltrato'] = 
   
            df_window_p['comp_precoces_traumatismos'] = 
            df_window_p['num_med_comp_precoces_traumatismos'] = 
            df_window_p['avg_comp_precoces_traumatismos'] = 
   
            df_window_p['comp_aten_med_qx_no_clasif'] = 
            df_window_p['num_med_comp_aten_med_qx_no_clasif'] = 
            df_window_p['avg_comp_aten_med_qx_no_clasif'] = 
   
            df_window_p['sec_traumatismos_envenenamiento_causas_ext'] = 
            df_window_p['num_med_sec_traumatismos_envenenamiento_causas_ext'] = 
            df_window_p['avg_sec_traumatismos_envenenamiento_causas_ext'] = 
   
            df_window_p['ot_efec_causas_ext_comp_traumatismos'] = 
            df_window_p['num_med_ot_efec_causas_ext_comp_traumatismos'] = 
            df_window_p['avg_ot_efec_causas_ext_comp_traumatismos'] = 
   
            df_window_p['tumores_malig_labio_bucal_faringe'] = 
            df_window_p['num_med_tumores_malig_labio_bucal_faringe'] = 
            df_window_p['avg_tumores_malig_labio_bucal_faringe'] = 

            # año_dx_dm año_dx_hta year_consulta
            # variable objetivo
            df_window_p['hta'] = 0
    """

2014-09-09T00:00:00.000000000
<class 'numpy.datetime64'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
2015-09-09 00:00:00

AttributeError: 'Timestamp' object has no attribute 'dt'